name: 3D Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
