name: 3D Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@1.0.0
        with:
          username: RuwanDilhara
          format: svg
          output_dir: ./profile-3d-contrib
          
      - name: Upload Generated Graph
        uses: actions/upload-artifact@v3
        with:
          name: 3d-contrib
          path: ./profile-3d-contrib
